-- SECCION: FLOTA
-- =============================================================================
-- 1200 · Fleet zone import
-- =============================================================================

alter table public.fleet
  add column if not exists zone text;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'fleet_zone_check'
      and conrelid = 'public.fleet'::regclass
  ) then
    alter table public.fleet
      add constraint fleet_zone_check
      check (zone is null or length(trim(zone)) between 1 and 120);
  end if;
end
$$;

comment on column public.fleet.zone is
  'Operational zone assigned to the bus in the imported fleet snapshot.';

create index if not exists fleet_zone_idx
  on public.fleet (zone)
  where zone is not null;

create index if not exists fleet_terminal_zone_idx
  on public.fleet (terminal_id, zone)
  where zone is not null;

create or replace function app.normalize_fleet_row()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.ppu := app.normalize_ppu(new.ppu);
  new.internal_number := app.normalize_code(new.internal_number);
  new.model := nullif(trim(coalesce(new.model, '')), '');
  new.subclass := nullif(trim(coalesce(new.subclass, '')), '');
  new.zone := nullif(regexp_replace(trim(coalesce(new.zone, '')), '\s+', ' ', 'g'), '');

  if new.ppu is null then
    raise exception 'PPU_REQUIRED' using errcode = '23514';
  end if;

  if new.internal_number is null then
    raise exception 'INTERNAL_NUMBER_REQUIRED' using errcode = '23514';
  end if;

  return new;
end;
$$;

create or replace view public.fleet_expiration_status
with (security_invoker = on) as
select
  f.id                          as fleet_id,
  f.internal_number,
  f.ppu,
  f.model,
  f.subclass,
  f.fuel_type,
  f.terminal_id,
  f.active,
  la.id                         as last_approved_event_id,
  la.expiration_date,
  la.return_at                  as last_approved_at,
  la.guide_number               as last_guide_number,
  case
    when la.expiration_date is null then 'NO_RECORD'
    when la.expiration_date < app.today_local() then 'EXPIRED'
    when la.expiration_date <= app.today_local() + app.expiring_soon_days() then 'EXPIRING_SOON'
    else 'VALID'
  end                           as expiration_status,
  (la.expiration_date - app.today_local()) as days_to_expiration,
  f.zone
from public.fleet f
left join lateral (
  select e.id, e.expiration_date, e.return_at, e.guide_number
  from public.technical_review_events e
  where e.fleet_id = f.id
    and e.status = 'CLOSED'
    and e.result = 'APPROVED'
  order by e.return_at desc, e.created_at desc
  limit 1
) la on true;

create or replace view public.fleet_view
with (security_invoker = on) as
select
  f.id,
  f.internal_number,
  f.ppu,
  f.model,
  f.subclass,
  f.fuel_type,
  ft.label        as fuel_type_label,
  f.terminal_id,
  t.name          as terminal_name,
  f.active,
  f.created_at,
  f.updated_at,
  f.zone
from public.fleet f
join public.terminals t on t.id = f.terminal_id
left join public.fleet_fuel_types ft on ft.code = f.fuel_type;

create temporary table tmp_fleet_import (
  internal_number text not null,
  ppu text not null,
  model text,
  subclass text,
  fuel_type text not null,
  zone text not null,
  terminal_name text,
  active boolean not null
) on commit drop;

insert into tmp_fleet_import (
  internal_number,
  ppu,
  model,
  subclass,
  fuel_type,
  zone,
  terminal_name,
  active
)
values
  ('2060', 'FLXS22', 'O500U 1826 59', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('2061', 'FLXS23', 'O500U 1826 59', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('2062', 'FLXS24', 'O500U 1826 59', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('2063', 'FLXS25', 'O500U 1826 59', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('2064', 'FLXS26', 'O500U 1826 59', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('2065', 'FLXS27', 'O500U 1826 59', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('2066', 'FLXS28', 'LO 916 45', 'A1', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('2067', 'FLXS29', 'LO 916 45', 'A1', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('2068', 'FLXS30', 'LO 916 45', 'A1', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('2069', 'FLXS31', 'OC 500 RF', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('617', 'FLXT12', 'B290R', 'B2', 'DIESEL', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('618', 'FLXT13', 'B290R', 'B2', 'DIESEL', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('619', 'FLXT69', 'B290R', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('620', 'FLXT70', 'B290R', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('621', 'FLXT71', 'B290R', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('622', 'FLXT72', 'B290R', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('623', 'FLXT73', 'B290R', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('624', 'FLXT74', 'B290R', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('625', 'FLXT75', 'B290R', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('626', 'FLXT76', 'B290R', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2070', 'FLXT77', 'LO 916 45', 'A1', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('2071', 'FLXT78', 'LO 916 45', 'A1', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('2072', 'FLXT79', 'LO 916 45', 'A1', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('2073', 'FLXT80', 'LO 916 45', 'A1', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('2074', 'FLXT81', 'LO 916 45', 'A1', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('2075', 'FLXT82', 'LO 916 45', 'A1', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('2076', 'FLXT83', 'LO 916 45', 'A1', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('2077', 'FLXT84', 'LO 916 45', 'A1', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('627', 'FLXT85', 'B290R', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('628', 'FLXT86', 'B290R', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('629', 'FLXT87', 'B290R', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('630', 'FLXT88', 'B290R', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('631', 'FLXT89', 'B290R', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('632', 'FLXT90', 'B290R', 'B', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('633', 'FLXT91', 'B8RLE', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('672', 'LDJW50', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('673', 'LDJW51', 'O 500U 1930', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('674', 'LDJW52', 'O 500U 1930', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('675', 'LDJW53', 'O 500U 1930', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('677', 'LDJX68', 'O 500U 1930', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('678', 'LDJX69', 'O 500U 1930', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('680', 'LDSW89', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('681', 'LDSW90', 'O 500U 1930', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('682', 'LDSX93', 'O 500U 1930', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('702', 'LDTB38', 'O 500U 1930', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('703', 'LDTB39', 'O 500U 1930', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('704', 'LDTB40', 'O 500U 1930', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('705', 'LDTB41', 'O 500U 1930', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('706', 'LDTB84', 'O 500U 1930', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('707', 'LDTB85', 'O 500U 1930', 'B2', 'DIESEL', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('708', 'LDTB86', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('709', 'LDTB87', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('710', 'LDTB88', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('711', 'LDTB89', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('712', 'LDTB90', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('713', 'LDTB91', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('714', 'LDTB92', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('715', 'LDTB93', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('716', 'LDTB94', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('717', 'LDTB95', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('718', 'LDTB96', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('719', 'LDTB97', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('720', 'LDTB98', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('721', 'LDTB99', 'O 500U 1930', 'B2', 'DIESEL', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('722', 'LDTC10', 'O 500U 1930', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('723', 'LDTC11', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('724', 'LDTC12', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('725', 'LDTC13', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('726', 'LDTC14', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('727', 'LDTC15', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('728', 'LDTC16', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('729', 'LDTF42', 'O 500U 1930', 'B2', 'DIESEL', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('730', 'LDTF43', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('731', 'LDTF44', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('732', 'LDTF45', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('733', 'LDTF46', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('734', 'LDTF47', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('735', 'LDTF48', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('736', 'LDTF49', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('737', 'LDTF50', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('738', 'LDTF51', 'O 500U 1930', 'B2', 'DIESEL', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('739', 'LDTG55', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('740', 'LDTG56', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('741', 'LDTG57', 'O 500U 1930', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('742', 'LDTG58', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('743', 'LDTG59', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('744', 'LDTG60', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('745', 'LDTG61', 'O 500U 1930', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('746', 'LDTG62', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('762', 'LFGJ98', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('763', 'LFGJ99', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('764', 'LFGK10', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('686', 'LFGL97', 'O 500U 1930', 'B2', 'DIESEL', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('687', 'LFGP20', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('688', 'LFGP21', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('689', 'LFGP22', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('690', 'LFGP23', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('691', 'LFGP24', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('692', 'LFGP25', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('693', 'LFGP26', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('701', 'LFSL97', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('700', 'LFSL98', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('765', 'LFSX97', 'O 500U 1930', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('768', 'LWTK42', 'XMQ 6127', 'B2', 'ELECTRIC', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('769', 'LWTK43', 'XMQ 6127', 'B2', 'ELECTRIC', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('770', 'LWTK44', 'XMQ 6127', 'B2', 'ELECTRIC', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('771', 'LWTK45', 'XMQ 6127', 'B2', 'ELECTRIC', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('772', 'LWTK46', 'XMQ 6127', 'B2', 'ELECTRIC', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('773', 'LWTK47', 'XMQ 6127', 'B2', 'ELECTRIC', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('774', 'LWTK48', 'XMQ 6127', 'B2', 'ELECTRIC', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('775', 'LWTK49', 'XMQ 6127', 'B2', 'ELECTRIC', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('776', 'LWTK50', 'XMQ 6127', 'B2', 'ELECTRIC', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('777', 'LWTK51', 'XMQ 6127', 'B2', 'ELECTRIC', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('778', 'LWTK52', 'XMQ 6127', 'B2', 'ELECTRIC', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('779', 'LWTK53', 'XMQ 6127', 'B2', 'ELECTRIC', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('780', 'LWTK54', 'XMQ 6127', 'B2', 'ELECTRIC', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('781', 'LWTK55', 'XMQ 6127', 'B2', 'ELECTRIC', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('782', 'LWTK56', 'XMQ 6127', 'B2', 'ELECTRIC', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('783', 'LWTK57', 'XMQ 6127', 'B2', 'ELECTRIC', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('784', 'LWTK58', 'XMQ 6127', 'B2', 'ELECTRIC', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('785', 'LWTK59', 'XMQ 6127', 'B2', 'ELECTRIC', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('786', 'LWTK60', 'XMQ 6127', 'B2', 'ELECTRIC', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('787', 'LWTK61', 'XMQ 6127', 'B2', 'ELECTRIC', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('788', 'LWTK62', 'XMQ 6127', 'B2', 'ELECTRIC', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('789', 'LWTK63', 'XMQ 6127', 'B2', 'ELECTRIC', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('790', 'LWTK64', 'XMQ 6127', 'B2', 'ELECTRIC', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('791', 'LWTK65', 'XMQ 6127', 'B2', 'ELECTRIC', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('792', 'LWTK66', 'XMQ 6127', 'B2', 'ELECTRIC', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1919', 'LXWP57', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1931', 'LXWP58', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1932', 'LXWP59', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1885', 'LXWP60', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1920', 'LXWP61', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1921', 'LXWP62', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1886', 'LXWP64', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1887', 'LXWP65', 'K320UA', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1693', 'LXWP66', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1854', 'LXWP67', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1855', 'LXWP68', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1856', 'LXWP69', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1857', 'LXWP70', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1858', 'LXWP71', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1859', 'LXWP72', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1860', 'LXWP73', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1861', 'LXWP74', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1862', 'LXWP75', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1694', 'LXWP76', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1695', 'LXWP77', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1863', 'LXWP78', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1864', 'LXWP79', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1865', 'LXWP80', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1696', 'LXWP81', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1866', 'LXWP82', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1867', 'LXWP83', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1697', 'LXWP85', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1698', 'LXWP86', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1888', 'LXWP87', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1699', 'PFTV77', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1889', 'PFTW19', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1890', 'PFTW20', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1700', 'PFTW25', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1891', 'PFTW26', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1868', 'PFTW28', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1869', 'PFTW29', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1870', 'PFTW30', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1871', 'PFTW31', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1701', 'PFTW32', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1872', 'PFTW34', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1892', 'PFTW35', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1702', 'PFTW36', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1873', 'PFTW38', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1893', 'PFTW39', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1703', 'PFTW40', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1894', 'PFTW41', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1895', 'PFTW42', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1874', 'PFTW44', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1875', 'PFTW45', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1704', 'PFTW46', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1876', 'PFTW47', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1896', 'PFTW48', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1877', 'PFTW49', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1878', 'PFTW50', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1897', 'PFTW51', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1898', 'PFTW55', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1879', 'PFTW56', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1705', 'PFTW57', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1880', 'PFTW58', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1899', 'PFTW59', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1706', 'PFTW60', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1900', 'PFTW61', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1901', 'PFTW62', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1902', 'PFVG75', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1903', 'PFVG76', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1904', 'PFVG77', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1707', 'PFVG78', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1881', 'PFVG79', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1708', 'PFVG80', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1709', 'PFVG82', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1710', 'PFVG83', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1711', 'PFVG85', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1712', 'PFVG86', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1713', 'PFVG87', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1714', 'PFVG88', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1905', 'PFVG89', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1906', 'PFVG90', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1907', 'PFVG92', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1908', 'PFVG93', 'K320UA', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1909', 'PFVG94', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1910', 'PFVG95', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1911', 'PFVG96', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1715', 'PFVG97', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1716', 'PFVG98', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1717', 'PFVG99', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1882', 'PFVH10', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1883', 'PFVH11', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1718', 'PFVH12', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1719', 'PFVH13', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1884', 'PFVH14', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1720', 'PFVH15', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1721', 'PFYC13', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1722', 'PFYC14', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1723', 'PFYC16', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1724', 'PFYC17', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1725', 'PFYC19', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1726', 'PFYC20', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1727', 'PFYC25', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1728', 'PFYC26', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1729', 'PFYC27', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1730', 'PFYC28', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1731', 'PFYC29', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1732', 'PFYC31', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1733', 'PFYC32', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1734', 'PFYC33', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1735', 'PFYC34', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1736', 'PFYC35', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1737', 'PFYC36', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1738', 'PFYC37', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1739', 'PFYC43', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1740', 'PFYC44', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1741', 'PFYC46', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1742', 'PFYC49', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1743', 'PFYC50', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1744', 'PFYC53', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1745', 'PFYC55', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1912', 'PFYC57', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1746', 'PFYC58', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1747', 'PFYC59', 'K320UA', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1748', 'PFYC60', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1749', 'PFYC61', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1750', 'PFYC62', 'K320UA', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1751', 'PFYC63', 'K320UA', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1752', 'PFYC64', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1753', 'PFYC65', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1922', 'PFYC66', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1754', 'PFYC68', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1755', 'PFYC69', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1756', 'PFYC70', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1757', 'PFYC72', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1923', 'PFYC75', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1924', 'PFYC76', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1913', 'PFYC77', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1758', 'PFYC79', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1933', 'PFYC80', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1759', 'PFYC81', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1760', 'PFYC82', 'K320UA', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1761', 'PFYC85', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1914', 'PFYC88', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1915', 'PFYC90', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1762', 'PFZK83', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1763', 'PFZK85', 'K320UA', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1764', 'PFZK87', 'K320UA', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1765', 'PFZK88', 'K320UA', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1927', 'PFZK91', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1766', 'PGBF42', 'K320UA', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1928', 'PGBF59', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1767', 'PGBY47', 'K320UA', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1768', 'PGBY52', 'K320UA', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1769', 'PGBY55', 'K320UA', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1770', 'PGBY56', 'K320UA', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1771', 'PGBY61', 'K320UA', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1916', 'PGBY67', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1929', 'PGBY72', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1930', 'PGBY73', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1772', 'PGBY74', 'K320UA', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1773', 'PGBY82', 'K320UA', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1774', 'PGBY83', 'K320UA', 'C2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1775', 'PGBY84', 'K320UA', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1776', 'PGBY85', 'K320UA', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1777', 'PGBY90', 'K320UA', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1778', 'PGBY91', 'K320UA', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1779', 'PGBY92', 'K320UA', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1780', 'PGBZ15', 'K320UA', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1781', 'PGKP67', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1782', 'PGLD42', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1783', 'PGLD59', 'K320UA', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1784', 'PGLD60', 'K320UA', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1785', 'PGLD62', 'K320UA', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1786', 'PGLD63', 'K320UA', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1917', 'PGLD67', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1787', 'PGLD68', 'K320UA', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1788', 'PGLD72', 'K320UA', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1789', 'PGLD82', 'K320UA', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1918', 'PGRZ67', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1925', 'PGTT95', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1926', 'PGTV12', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1790', 'PGTV13', 'K320UA', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1791', 'PGWT98', 'K280UB', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('832', 'SGPW34', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('833', 'SGPW35', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('834', 'SGPW36', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('835', 'SGPW37', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('836', 'SGPW38', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('837', 'SGPW39', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('838', 'SGPW40', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('839', 'SGPW41', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('840', 'SGPW42', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('841', 'SGPW43', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('842', 'SGPW44', 'B8RLE', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('843', 'SGPW45', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('844', 'SGPW46', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('845', 'SGPW47', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('846', 'SGPW48', 'B8RLE', 'A2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('847', 'SGPW49', 'B8RLE', 'A2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('848', 'SGPW50', 'B8RLE', 'A2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('849', 'SGPW51', 'B8RLE', 'A2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('850', 'SGPW52', 'B8RLE', 'A2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('851', 'SGPW53', 'B8RLE', 'A2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('852', 'SGPW54', 'B8RLE', 'A2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('853', 'SGPX10', 'B8RLE', 'A2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('854', 'SGPX11', 'B8RLE', 'A2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('855', 'SGPX12', 'B8RLE', 'A2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('856', 'SGPX13', 'B8RLE', 'A2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('857', 'SGPY23', 'B8RLE', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('858', 'SGPY24', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('859', 'SGPY55', 'B8RLE', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('860', 'SGPY56', 'B8RLE', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('861', 'SGPY57', 'B8RLE', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('862', 'SGPY58', 'B8RLE', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('863', 'SGPY59', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('864', 'SGPY60', 'B8RLE', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('865', 'SGPY61', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('866', 'SGPY62', 'B8RLE', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('867', 'SGPY63', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('868', 'SGPY64', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('869', 'SGPY65', 'B8RLE', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('870', 'SGPY66', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('871', 'SGPY67', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('872', 'SGPY68', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('873', 'SGPY69', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('874', 'SGPY70', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('875', 'SGPY71', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('876', 'SGPY72', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('877', 'SGPY73', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('878', 'SGPY74', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('879', 'SGPY75', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('880', 'SGPY76', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('881', 'SGPY77', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('882', 'SGPY78', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('883', 'SGPY79', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('884', 'SGPY80', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('885', 'SGPY81', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('886', 'SGPY82', 'B8RLE', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('887', 'SGPY83', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('888', 'SGPY84', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('889', 'SGPY85', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('890', 'SGPY86', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('891', 'SGPY87', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('892', 'SGPY88', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('893', 'SGPY89', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('894', 'SGPY90', 'B8RLE', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('895', 'SGPY91', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('896', 'SGPY92', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('897', 'SGPY93', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('898', 'SGPY94', 'B8RLE', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('899', 'SGPY95', 'B8RLE', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('900', 'SHCV64', 'B8RLE', 'A2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1502', 'SHCV68', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('902', 'SHCV69', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1503', 'SHCV70', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1504', 'SHCV71', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1505', 'SHCV72', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1506', 'SHCV73', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('907', 'SHCV74', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('908', 'SHCV75', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('909', 'SHCV76', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('910', 'SHCV77', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('911', 'SHCV78', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('912', 'SHCV79', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('913', 'SHCV80', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('914', 'SHCV81', 'B8RLE', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('915', 'SHCV82', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('916', 'SHCV83', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('917', 'SHCV84', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('918', 'SHCV85', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('919', 'SHCX36', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('920', 'SHCX37', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('921', 'SHCX38', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('922', 'SHCX39', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1934', 'SHCX40', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('923', 'SHCX42', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('924', 'SHCX55', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('925', 'SHCX56', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('926', 'SHCX57', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('927', 'SHCX59', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('928', 'SHCX62', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('929', 'SHCX63', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('930', 'SHCX64', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('931', 'SHCY12', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('932', 'SHCY13', 'B8RLE', 'A2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('933', 'SHCY14', 'B8RLE', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('934', 'SHCY20', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('935', 'SHCY21', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('936', 'SHCY22', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('937', 'SHCY23', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('938', 'SHCY24', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('939', 'SHCY25', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('940', 'SHCY26', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('941', 'SHCY27', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('942', 'SHCY28', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('943', 'SHCY29', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('944', 'SHCY30', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('945', 'SHCY31', 'B8RLE', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('946', 'SHCY52', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('947', 'SHCY53', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('948', 'SHCY54', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('949', 'SHCY99', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1445', 'SHXD58', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1446', 'SHXD59', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1447', 'SHXD60', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1792', 'SHXD61', 'B8RLE', 'A2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1793', 'SHXD62', 'B8RLE', 'A2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1794', 'SHXD63', 'B8RLE', 'A2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1795', 'SHXD64', 'B8RLE', 'A2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1796', 'SHXD65', 'B8RLE', 'A2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1797', 'SHXD66', 'B8RLE', 'A2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1798', 'SHXD67', 'B8RLE', 'A2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1448', 'SHXD68', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1449', 'SHXD69', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1450', 'SHXD70', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1451', 'SHXD71', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1452', 'SHXD72', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1453', 'SHXD73', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1454', 'SHXD74', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('1455', 'SHXD75', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1456', 'SHXD77', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1457', 'SHXD79', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1458', 'SHXD80', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('1799', 'SHXD81', 'B8RLE', 'A2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1459', 'SHXD85', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1460', 'SHXF13', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1461', 'SHXF14', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1800', 'SHXF15', 'B8RLE', 'A2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1801', 'SHXF16', 'B8RLE', 'A2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1802', 'SHXF17', 'B8RLE', 'A2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1462', 'SHXF29', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1463', 'SHXF31', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1464', 'SHXF32', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('1465', 'SHXF84', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1466', 'SHXF85', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1935', 'SHXF86', 'B8RLE', 'A2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1467', 'SHXF87', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1468', 'SHXF88', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1936', 'SHXF89', 'B8RLE', 'A2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1469', 'SHXF90', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1937', 'SHXF91', 'B8RLE', 'A2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1470', 'SHXF92', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1471', 'SHXF93', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1938', 'SHXF94', 'B8RLE', 'A2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1939', 'SHXF95', 'B8RLE', 'A2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1940', 'SHXF96', 'B8RLE', 'A2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1472', 'SHXF97', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1803', 'SHXF98', 'B8RLE', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1804', 'SHXF99', 'B8RLE', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1473', 'SHXG33', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1474', 'SHXG35', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1475', 'SHXG36', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1941', 'SHXG37', 'B8RLE', 'A2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1476', 'SHXG38', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1477', 'SHXG39', 'B8RLE', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1594', 'SHXG40', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('1478', 'SHXG41', 'B8RLE', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1595', 'SHXG42', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('1479', 'SHXG43', 'B8RLE', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1480', 'SHXG44', 'B8RLE', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1596', 'SHXG45', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('1597', 'SHXG81', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('1598', 'SHXG82', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('1599', 'SHXG83', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('1600', 'SHXG84', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('1601', 'SHXG85', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('1602', 'SHXG96', 'B8RLE', 'B2', 'DIESEL', 'US6 LO BARNECHEA', 'Terminal El Salto', true),
  ('1603', 'SHXG97', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('1604', 'SHXG98', 'B8RLE', 'B2', 'DIESEL', 'US6 LO BARNECHEA', 'Terminal El Salto', true),
  ('1605', 'SJPB19', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('1606', 'SJPB21', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1607', 'SJPB22', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('1608', 'SJPB23', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('1609', 'SJPB24', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('1610', 'SJPB25', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1942', 'SJPB27', 'B8RLE', 'A2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1611', 'SJPB28', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('1612', 'SJPB29', 'B8RLE', 'B2', 'DIESEL', 'US6 LO BARNECHEA', 'Terminal El Salto', true),
  ('1613', 'SJPB30', 'B8RLE', 'B2', 'DIESEL', 'US6 LO BARNECHEA', 'Terminal El Salto', true),
  ('1614', 'SJPB31', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('1615', 'SJPB32', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('1616', 'SJPB33', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('1617', 'SJPB34', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('1618', 'SJPB35', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('1619', 'SJPB36', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('1620', 'SJPB37', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('1621', 'SJPB38', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('1943', 'SJPB65', 'B8RLE', 'A2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1944', 'SJPB67', 'B8RLE', 'A2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1622', 'SJPC15', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('1623', 'SJPC16', 'B8RLE', 'B2', 'DIESEL', 'US6 LO BARNECHEA', 'Terminal El Salto', true),
  ('1481', 'SJPC17', 'B8RLE', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1624', 'SJPC18', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('1945', 'SJPC19', 'B8RLE', 'A2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1625', 'SJPC20', 'B8RLE', 'B2', 'DIESEL', 'US6 LO BARNECHEA', 'Terminal El Salto', true),
  ('1946', 'SJPC21', 'B8RLE', 'A2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1482', 'SJPC22', 'B8RLE', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1483', 'SJPC23', 'B8RLE', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1484', 'SJPC24', 'B8RLE', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1485', 'SJPC25', 'B8RLE', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1626', 'SJPC26', 'B8RLE', 'B2', 'DIESEL', 'US6 LO BARNECHEA', 'Terminal El Salto', true),
  ('1627', 'SJPC27', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('1486', 'SJPC28', 'B8RLE', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1805', 'SJPC29', 'B8RLE', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1628', 'SJPC32', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('1629', 'SJPC46', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('1630', 'SJPC47', 'B8RLE', 'B2', 'DIESEL', 'US6 LO BARNECHEA', 'Terminal El Salto', true),
  ('1631', 'SJPC51', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('1632', 'SJPC69', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('1633', 'SJPC70', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('1634', 'SJPC71', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('1635', 'SJPC72', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1636', 'SJPC73', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1947', 'SJPC74', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1637', 'SJPC76', 'B8RLE', 'B2', 'DIESEL', 'US6 LO BARNECHEA', 'Terminal El Salto', true),
  ('1638', 'SJPC77', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('1948', 'SJPC78', 'B8RLE', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1639', 'SJPC79', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('1640', 'SJPC80', 'B8RLE', 'B2', 'DIESEL', 'US6 LO BARNECHEA', 'Terminal El Salto', true),
  ('1641', 'SJPC81', 'B8RLE', 'B2', 'DIESEL', 'US6 LO BARNECHEA', 'Terminal El Salto', true),
  ('1642', 'SJPC82', 'B8RLE', 'B2', 'DIESEL', 'US6 LO BARNECHEA', 'Terminal El Salto', true),
  ('1643', 'SJPC83', 'B8RLE', 'B2', 'DIESEL', 'US6 LO BARNECHEA', 'Terminal El Salto', true),
  ('1644', 'SJPC84', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1645', 'SJPC85', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('1646', 'SJPD41', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1647', 'SJPD42', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1648', 'SJPD43', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1649', 'SJPD44', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1650', 'SJPD45', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1651', 'SJPD55', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1652', 'SJPD56', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1949', 'SJPD57', 'B8RLE', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1653', 'SJPD58', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1654', 'SJPD70', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1655', 'SJPD71', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1656', 'SJPD72', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1950', 'SJPD74', 'B8RLE', 'A2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1657', 'SJPD75', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1487', 'SJPD76', 'B8RLE', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1488', 'SJPD77', 'B8RLE', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1489', 'SJPD78', 'B8RLE', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1658', 'SJPD79', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1659', 'SJPD80', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1660', 'SJPD81', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1661', 'SJPD82', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1951', 'SJPD83', 'B8RLE', 'C2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1662', 'SJPD84', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1490', 'SJPD85', 'B8RLE', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1663', 'SJPD97', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1664', 'SJPF40', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1665', 'SJPF41', 'B8RLE', 'B2', 'DIESEL', 'US6 LO BARNECHEA', 'Terminal El Salto', true),
  ('1666', 'SJPF42', 'B8RLE', 'B2', 'DIESEL', 'US6 LO BARNECHEA', 'Terminal El Salto', true),
  ('1667', 'SJPF43', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1668', 'SJPF44', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1669', 'SJPF83', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1670', 'SJPF84', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1671', 'SJPF85', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1672', 'SJPF91', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1673', 'SJPF92', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1674', 'SJPF93', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1675', 'SJPF94', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1676', 'SJPF95', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1677', 'SJPF96', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1678', 'SJPF97', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1679', 'SJPF98', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1680', 'SJPF99', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1370', 'SKDF67', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1371', 'SKDF77', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1372', 'SKDF78', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1373', 'SKDF79', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1374', 'SKDF82', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1375', 'SKDF88', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1376', 'SKDF92', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1377', 'SKDF95', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1378', 'SKDF98', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1379', 'SKDF99', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1380', 'SKDG11', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1381', 'SKDG15', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1382', 'SKDG18', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1383', 'SKDG24', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1384', 'SKDG26', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1385', 'SKDG28', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1386', 'SKDG29', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1387', 'SKDG39', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1388', 'SKDG40', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1389', 'SKDG43', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1390', 'SKDG52', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1391', 'SKDG69', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1392', 'SKDG73', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1393', 'SKDG80', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1394', 'SKDG81', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1395', 'SKDG85', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1396', 'SKDG90', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1397', 'SKDG93', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1398', 'SKDG96', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1399', 'SKDG98', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1400', 'SKDH29', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1401', 'SKDH30', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1402', 'SKDH34', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1403', 'SKDH41', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1404', 'SKDH59', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1405', 'SKDH61', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1406', 'SKDH62', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1407', 'SKDH63', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1408', 'SKDH69', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1409', 'SKDH71', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1410', 'SKDH73', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1411', 'SKDH78', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1412', 'SKDH79', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1413', 'SKDH82', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1414', 'SKDH85', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1415', 'SKDH90', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1416', 'SKDH95', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1417', 'SKDH97', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1418', 'SKDJ10', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1419', 'SKDJ11', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1420', 'SKDJ14', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1421', 'SKDJ18', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1422', 'SKDJ19', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1423', 'SKDJ25', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1424', 'SKDJ31', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1425', 'SKDJ33', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1426', 'SKDJ67', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1427', 'SKDJ69', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1428', 'SKDJ73', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1429', 'SKDJ74', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1430', 'SKDJ75', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1431', 'SKDJ76', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1433', 'SKDJ78', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1434', 'SKDJ79', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1435', 'SKDJ80', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1436', 'SKDJ82', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1437', 'SKDJ84', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1438', 'SKDJ86', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1439', 'SKDJ87', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1440', 'SKDJ88', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1441', 'SKDJ90', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1442', 'SKDJ93', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1443', 'SKDJ94', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1444', 'SKDJ95', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('1989', 'SKJP39', 'U 10', 'A2', 'ELECTRIC', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1681', 'SKPH68', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1491', 'SKPH69', 'B8RLE', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1682', 'SKPH70', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1683', 'SKPH72', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1684', 'SKPH73', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1685', 'SKPH74', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1686', 'SKPH75', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1952', 'SKPH76', 'B8RLE', 'A2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1687', 'SKPH77', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1688', 'SKPH78', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('1492', 'SKPH79', 'B8RLE', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1953', 'SKPH80', 'B8RLE', 'C2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1689', 'SKPH81', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1690', 'SKPH82', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1691', 'SKPH83', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1954', 'SKPJ40', 'B8RLE', 'C2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1955', 'SKPJ41', 'B8RLE', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1956', 'SKPJ42', 'B8RLE', 'C2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1692', 'SKPJ43', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1806', 'SKPJ44', 'B8RLE', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1493', 'SKPJ45', 'B8RLE', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1494', 'SKPJ46', 'B8RLE', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1957', 'SKPJ47', 'B8RLE', 'C2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1495', 'SKPJ48', 'B8RLE', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1496', 'SKPJ49', 'B8RLE', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1807', 'SKPJ50', 'B8RLE', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1958', 'SKPJ51', 'B8RLE', 'C2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1808', 'SKPJ52', 'B8RLE', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1497', 'SKPJ53', 'B8RLE', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1498', 'SKPJ54', 'B8RLE', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1809', 'SKPJ75', 'B8RLE', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1810', 'SKPJ76', 'B8RLE', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1811', 'SKPJ78', 'B8RLE', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1812', 'SKPJ79', 'B8RLE', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1813', 'SKPJ80', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1814', 'SKPJ81', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1815', 'SKPJ82', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1816', 'SKPJ83', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1817', 'SKPJ84', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1818', 'SKPJ85', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1819', 'SKPJ86', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1820', 'SKPJ87', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1821', 'SKPJ89', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1822', 'SKPJ90', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1499', 'SKPK17', 'B8RLE', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1823', 'SKPK18', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1824', 'SKPK19', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1825', 'SKPK20', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1826', 'SKPK21', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1827', 'SKPK22', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1828', 'SKPK23', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1959', 'SKPK24', 'B8RLE', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1829', 'SKPK25', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1830', 'SKPK26', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1831', 'SKPK27', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1832', 'SKPK28', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1960', 'SKPK29', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1833', 'SKPK30', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('1834', 'SKPK31', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1835', 'SKPK32', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1836', 'SKPK33', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1837', 'SKPK34', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1838', 'SKPK35', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1961', 'SKPK36', 'B8RLE', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1839', 'SKPK37', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1962', 'SKPK38', 'B8RLE', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1840', 'SKPK39', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1841', 'SKPK40', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1842', 'SKPK41', 'B8RLE', 'B2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1843', 'SKPK42', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1844', 'SKPK44', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1845', 'SKPK45', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1500', 'SKPK59', 'B8RLE', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1501', 'SKPK60', 'B8RLE', 'C2', 'DIESEL', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1963', 'SKPK61', 'B8RLE', 'C2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1846', 'SKPK62', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1847', 'SKPK63', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1964', 'SKPL24', 'B8RLE', 'C2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1965', 'SKPL25', 'B8RLE', 'C2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1966', 'SKPL26', 'B8RLE', 'C2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1967', 'SKPL27', 'B8RLE', 'C2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1848', 'SKPL28', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1968', 'SKPL29', 'B8RLE', 'C2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1849', 'SKPL30', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1969', 'SKPL31', 'B8RLE', 'C2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1970', 'SKPL32', 'B8RLE', 'C2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1850', 'SKPL33', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1851', 'SKPL34', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1971', 'SKPL35', 'B8RLE', 'C2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1852', 'SKPL36', 'B8RLE', 'B2', 'DIESEL', 'US6 EL ROBLE', 'Terminal El Roble', true),
  ('1853', 'SKPL37', 'B8RLE', 'B2', 'DIESEL', 'US6 COLO COLO', 'Terminal Colo Colo', true),
  ('1972', 'SKPL38', 'B8RLE', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1973', 'SKPP14', 'B8RLE', 'C2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1974', 'SKPP15', 'B8RLE', 'C2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1975', 'SKPP16', 'B8RLE', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1976', 'SKPP17', 'B8RLE', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1977', 'SKPP18', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1978', 'SKPP19', 'B8RLE', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1979', 'SKPP20', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1980', 'SKPP21', 'B8RLE', 'C2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1981', 'SKPP22', 'B8RLE', 'B2', 'DIESEL', 'US4 LO BARNECHEA', 'Terminal El Salto', true),
  ('1982', 'SKPP23', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1983', 'SKPP24', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1984', 'SKPP25', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1985', 'SKPP26', 'B8RLE', 'C2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1990', 'SKPR99', 'U 10', 'A2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1991', 'SKPS10', 'U 10', 'A2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1992', 'SKPS15', 'U 10', 'A2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1993', 'SKPS19', 'U 10', 'A2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1994', 'SKPS20', 'U 10', 'A2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1995', 'SKPS21', 'U 10', 'A2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1996', 'SKPS22', 'U 10', 'A2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1997', 'SKPS25', 'U 10', 'A2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1998', 'SKPS31', 'U 10', 'A2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1999', 'SKPS32', 'U 10', 'A2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2000', 'SKPS34', 'U 10', 'A2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2001', 'SKPS44', 'U 10', 'A2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2002', 'SKPS47', 'U 10', 'A2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2003', 'SKPS48', 'U 10', 'A2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2004', 'SKPS49', 'U 10', 'A2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1507', 'SLGS86', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1508', 'SLGS87', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1509', 'SLGS89', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1510', 'SLGS90', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1511', 'SLGS92', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1512', 'SLGS94', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1513', 'SLGS95', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1514', 'SLGS96', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1515', 'SLGS98', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1516', 'SLGS99', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1517', 'SLGT10', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1518', 'SLGT13', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1519', 'SLGT27', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1520', 'SLGT29', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1521', 'SLGT31', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1522', 'SLGT32', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1523', 'SLGT34', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1524', 'SLGT36', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1525', 'SLGT37', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1526', 'SLGT38', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1527', 'SLLY52', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1528', 'SLLY78', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1529', 'SLLY81', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1530', 'SLLY86', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1531', 'SLLY91', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1532', 'SLLY99', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1533', 'SLLZ26', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1534', 'SLLZ29', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1535', 'SLLZ31', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1536', 'SLLZ36', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1537', 'SLLZ38', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1538', 'SLLZ39', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1539', 'SLLZ40', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1540', 'SLLZ43', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1541', 'SLLZ46', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1542', 'SLLZ47', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1543', 'SLLZ51', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1544', 'SLLZ56', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1545', 'SLLZ63', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1546', 'SLLZ77', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1547', 'SLLZ93', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1548', 'SLLZ98', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1549', 'SLPB18', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1550', 'SLPB29', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1551', 'SLPB36', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1552', 'SLPB44', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1553', 'SLPB45', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1554', 'SLPB47', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1555', 'SLPB49', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1556', 'SLPB53', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1557', 'SLPB64', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1558', 'SLPB66', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1559', 'SLPB69', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1560', 'SLPB71', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1561', 'SLPB73', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1562', 'SLPB83', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1563', 'SLPB84', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1564', 'SLPB86', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1565', 'SLPB87', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1566', 'SLPB92', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1567', 'SLPB94', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1568', 'SLPB98', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1569', 'SLPC10', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1570', 'SLPC11', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1571', 'SLPC12', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1572', 'SLPC14', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1573', 'SLPC18', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1574', 'SLPC22', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1575', 'SLPC24', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1576', 'SLPC25', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1577', 'SLPC26', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1578', 'SLPC27', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1579', 'SLPC29', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1580', 'SLPC30', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1581', 'SLPC32', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1582', 'SLPC36', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1583', 'SLPC38', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1584', 'SLPC40', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1585', 'SLPC41', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1586', 'SLPC43', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1587', 'SLPC48', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1588', 'SLPC49', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1589', 'SLPC50', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1590', 'SLPC51', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1591', 'SLPC52', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1592', 'SLPC54', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1593', 'SLPC58', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('1986', 'SLYB60', 'B8RLE', 'C2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1987', 'SLYB61', 'B8RLE', 'B2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('1988', 'SLYB62', 'B8RLE', 'C2', 'DIESEL', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2005', 'SPCG32', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('2006', 'SPCG34', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('2007', 'SPCG35', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('2008', 'SPCG36', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2009', 'SPCG40', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('2010', 'SPCG41', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('2011', 'SPCG42', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2012', 'SPCG43', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2013', 'SPCG44', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2014', 'SPCG46', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2015', 'SPCG47', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2016', 'SPCG48', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2017', 'SPCG49', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2018', 'SPCG50', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2019', 'SPCG51', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2020', 'SPCG52', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2021', 'SPCG53', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2022', 'SPCG54', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2023', 'SPCG55', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2024', 'SPCG56', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2025', 'SPCG59', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2026', 'SPCG62', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2027', 'SPCG63', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2028', 'SPCG64', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2029', 'SPCG65', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2030', 'SPCG66', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2031', 'SPCG68', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2032', 'SPCG69', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2033', 'SPCG70', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2034', 'SPCG71', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2035', 'SPCG72', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2036', 'SPCG73', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2037', 'SPCG74', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2038', 'SPCG75', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2039', 'SPCG77', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2040', 'SPCG78', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2041', 'SPCG79', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('2042', 'SPCG80', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('2043', 'SPCG81', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('2044', 'SPCG82', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 COLO COLO', 'Terminal Colo Colo', true),
  ('2045', 'SPCG83', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2046', 'SPCG84', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2047', 'SPCG85', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2048', 'SPCG86', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2049', 'SPCG87', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2050', 'SPCG88', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2051', 'SPCG89', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2052', 'SPCG90', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2053', 'SPCG93', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2054', 'SPCG94', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2055', 'SPCG95', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2056', 'SPCG97', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2057', 'SPCG98', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2058', 'SPCG99', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2059', 'SPGD41', 'EBUS U12 SC', 'B2', 'ELECTRIC', 'US4 ESCUELA MILITAR', 'Terminal El Salto', true),
  ('2078', 'STVR85', 'XMQ6900G ETECH', null, 'ELECTRIC', 'REDVAN', null, true),
  ('2079', 'STVS22', 'XMQ6900G ETECH', null, 'ELECTRIC', 'REDVAN', null, true),
  ('2080', 'TWDH51', 'XMQ6900G ETECH', null, 'ELECTRIC', 'REDVAN', null, true),
  ('2081', 'TWDH54', 'XMQ6900G ETECH', null, 'ELECTRIC', 'REDVAN', null, true),
  ('2084', 'VHDF74', 'XMQ 6127', 'B', 'ELECTRIC', 'US6 LO ECHEVERS', 'Terminal Lo Echevers', true),
  ('2082', 'VHLS23', 'XMQ6900G ETECH', 'A1', 'ELECTRIC', 'REDVAN', null, true),
  ('2083', 'VHPG45', 'XMQ6900G ETECH', 'A1', 'ELECTRIC', 'REDVAN', null, true);

update tmp_fleet_import
set model = nullif(trim(coalesce(model, '')), ''),
    subclass = nullif(trim(coalesce(subclass, '')), ''),
    zone = nullif(regexp_replace(trim(coalesce(zone, '')), '\s+', ' ', 'g'), ''),
    terminal_name = nullif(regexp_replace(trim(coalesce(terminal_name, '')), '\s+', ' ', 'g'), '');

-- REDVAN rows come without terminal in the source sheet.
update tmp_fleet_import
set terminal_name = 'Terminal Redvan'
where terminal_name is null
  and zone = 'REDVAN';

do $$
begin
  if exists (select 1 from tmp_fleet_import where zone is null) then
    raise exception 'FLEET_IMPORT_ZONE_REQUIRED';
  end if;

  if exists (select 1 from tmp_fleet_import where terminal_name is null) then
    raise exception 'FLEET_IMPORT_TERMINAL_REQUIRED';
  end if;

  if exists (select 1 from tmp_fleet_import where fuel_type not in ('DIESEL', 'ELECTRIC')) then
    raise exception 'FLEET_IMPORT_UNKNOWN_FUEL_TYPE';
  end if;

  if exists (select ppu from tmp_fleet_import group by ppu having count(*) > 1) then
    raise exception 'FLEET_IMPORT_DUPLICATE_PPU';
  end if;

  if exists (
    select internal_number
    from tmp_fleet_import
    group by internal_number
    having count(*) > 1
  ) then
    raise exception 'FLEET_IMPORT_DUPLICATE_INTERNAL_NUMBER';
  end if;
end
$$;

insert into public.terminals (name, active)
select distinct i.terminal_name, true
from tmp_fleet_import i
where not exists (
  select 1
  from public.terminals t
  where lower(trim(t.name)) = lower(trim(i.terminal_name))
);

update public.terminals t
set active = true
where t.active is false
  and exists (
    select 1
    from tmp_fleet_import i
    where lower(trim(i.terminal_name)) = lower(trim(t.name))
  );

with resolved as (
  select
    i.internal_number,
    i.ppu,
    i.model,
    i.subclass,
    i.fuel_type,
    i.zone,
    t.id as terminal_id,
    i.active
  from tmp_fleet_import i
  join public.terminals t
    on lower(trim(t.name)) = lower(trim(i.terminal_name))
)
update public.fleet f
set internal_number = r.internal_number,
    ppu = r.ppu,
    model = r.model,
    subclass = r.subclass,
    fuel_type = r.fuel_type,
    zone = r.zone,
    terminal_id = r.terminal_id,
    active = r.active
from resolved r
where f.ppu = r.ppu
   or f.internal_number = r.internal_number;

with resolved as (
  select
    i.internal_number,
    i.ppu,
    i.model,
    i.subclass,
    i.fuel_type,
    i.zone,
    t.id as terminal_id,
    i.active
  from tmp_fleet_import i
  join public.terminals t
    on lower(trim(t.name)) = lower(trim(i.terminal_name))
)
insert into public.fleet (
  internal_number,
  ppu,
  model,
  subclass,
  fuel_type,
  zone,
  terminal_id,
  active
)
select
  r.internal_number,
  r.ppu,
  r.model,
  r.subclass,
  r.fuel_type,
  r.zone,
  r.terminal_id,
  r.active
from resolved r
where not exists (
  select 1
  from public.fleet f
  where f.ppu = r.ppu
     or f.internal_number = r.internal_number
);
